spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gymdb
    username: postgres
    password: 1105
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8079
