package com.gymcrm.gymservice;

import com.gymcrm.dao.TraineeRepository;
import com.gymcrm.model.Trainee;
import com.gymcrm.service.impl.TraineeServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class TraineeServiceTest {

    @Mock
    private TraineeRepository traineeRepository;

    @InjectMocks
    private TraineeServiceImpl traineeService;

    @BeforeEach
    void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void testCreateTrainee_UserNameDoesNotExist() {
        Trainee trainee = new Trainee();
        trainee.setId(1L);
        trainee.setFirstName("John");
        trainee.setLastName("Doe");

        when(traineeRepository.existsByUsername("John.Doe")).thenReturn(false);

        Trainee created = traineeService.createTrainee(trainee);

        assertNotNull(created.getId(), "ID should be generated by the service");
        assertNotNull(created.getPassword(), "Password should be generated by the service");
        assertEquals(10, created.getPassword().length(), "Password should be of length 10");
        assertEquals("John.Doe", created.getUsername(), "Username should be firstName.lastName");

        verify(traineeRepository, times(1)).create(any(Trainee.class));
    }

    @Test
    void testCreateTrainee_UserNameExistsOnce() {
        Trainee trainee = new Trainee();
        trainee.setId(1L);
        trainee.setFirstName("John");
        trainee.setLastName("Doe");

        when(traineeRepository.existsByUsername("John.Doe")).thenReturn(true);
        when(traineeRepository.existsByUsername("John.Doe1")).thenReturn(false);

        Trainee created = traineeService.createTrainee(trainee);

        assertEquals("John.Doe1", created.getUsername(), "Username should be firstName.lastName1");

        verify(traineeRepository, times(1)).create(any(Trainee.class));
    }

    @Test
    void testCreateTrainee_UserNameExistsTwice() {
        Trainee trainee = new Trainee();
        trainee.setId(3L);
        trainee.setFirstName("John");
        trainee.setLastName("Doe");

        when(traineeRepository.existsByUsername("John.Doe")).thenReturn(true);
        when(traineeRepository.existsByUsername("John.Doe1")).thenReturn(true);
        when(traineeRepository.existsByUsername("John.Doe2")).thenReturn(false);

        Trainee created = traineeService.createTrainee(trainee);

        assertEquals("John.Doe2", created.getUsername(), "Username should be firstName.lastName2");

        verify(traineeRepository, times(1)).create(any(Trainee.class));
    }

    @Test
    void testUpdateTrainee() {
        Trainee existing = new Trainee();
        existing.setId(10L);
        existing.setFirstName("Jane");

        traineeService.updateTrainee(existing);

        verify(traineeRepository, times(1)).update(existing);
    }

    @Test
    void testDeleteTrainee() {
        Long traineeId = 5L;

        traineeService.deleteTrainee(traineeId);

        verify(traineeRepository, times(1)).delete(traineeId);
    }

    @Test
    void testGetTrainee() {
        Long traineeId = 2L;
        Trainee mockTrainee = new Trainee();
        mockTrainee.setId(traineeId);
        mockTrainee.setFirstName("Mark");

        when(traineeRepository.read(traineeId)).thenReturn(mockTrainee);

        Trainee result = traineeService.getTrainee(traineeId);

        assertNotNull(result, "Should return the trainee from DAO");
        assertEquals("Mark", result.getFirstName());
        verify(traineeRepository, times(1)).read(traineeId);
    }

    @Test
    void testGetAllTrainees() {
        Trainee t1 = new Trainee();
        Trainee t2 = new Trainee();
        when(traineeRepository.findAll()).thenReturn(Arrays.asList(t1, t2));

        List<Trainee> all = traineeService.getAllTrainees();

        assertEquals(2, all.size());
        verify(traineeRepository, times(1)).findAll();
    }
}
